Module12 task1
htmlacademy-javascript/1806037-kekstagram-24 pull request #15
Opened 2021-11-09 18:00 UTC by FirstBroRussia

2021-11-09 19:20 UTC, copperkraft commented on js/api.js
> +      setOperationToCloseSuccessPopup();
В чем разница двух веток?

2021-11-09 19:44 UTC, copperkraft requested changes

2021-11-09 19:44 UTC, copperkraft commented on js/form.js
> +    fileUploaderButton.setCustomValidity('Неподдерживаемый формат файла\nТолько: .jpeg, .jpg, .png');
Я бы список форматов все-таки брал из твоего VALID_FILE_EXTENSIONS.

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +  while (uniqueValues.length < 25) {
25 в константу.

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +    item = items[uniqueValues[index]];
Не переприсваивай параметр, лучше заводить отдельную переменную с другим названием. 
В данном же случае я бы вообще убрал присваивание, просто возвращал бы `items[uniqueValues[index]]`

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +    return item;
Это все можно написать следующим образом: 
```js
return {
  ...item,
  commentsListLength: item.comments.length
}
```

Обрати внимание, что не стоит использовать слово Object в именовании переменных, т.к. это не имеет много смысла. 
То же можно сказать про слово element. Также я бы оставил слово element для случаев, когда ты работаешь с DOM элементами.

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +    if (evt.target.closest('#filter-default')) {
Может вынесешь эти три ветки в функции?

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +  let setTimeOutOperation;
set предполагает что это функция. 
timeout это одно слово. 
Я бы упростил название до timeout

2021-11-09 19:44 UTC, copperkraft commented on js/photo-filtering.js
> +      }, 500);
Таймаут в константу.

2021-11-09 19:44 UTC, copperkraft commented on js/render-full-picture.js
> +  if (currentPhoto) {
Я люблю трюк, когда ты пишешь 
```js
if (!currentPhoto) { 
  return; 
} 
```
И пишешь код как ни в чем не бывало. Помогает избегать вложенности из нескольких `if()`

2021-11-10 07:50 UTC, FirstBroRussia commented on js/api.js
> +      setOperationToCloseSuccessPopup();
+

2021-11-10 07:50 UTC, FirstBroRussia commented on js/form.js
> +    fileUploaderButton.setCustomValidity('Неподдерживаемый формат файла\nТолько: .jpeg, .jpg, .png');
+

2021-11-10 07:50 UTC, FirstBroRussia commented on js/photo-filtering.js
> +  while (uniqueValues.length < 25) {
+

2021-11-10 07:50 UTC, FirstBroRussia commented on js/photo-filtering.js
> +    item = items[uniqueValues[index]];
+

2021-11-10 07:53 UTC, FirstBroRussia commented on js/photo-filtering.js
> +    return item;
вот тут спасибо! долго думал как так сделать, теперь буду знать

2021-11-10 08:04 UTC, FirstBroRussia commented on js/photo-filtering.js
> +    if (evt.target.closest('#filter-default')) {
+++

2021-11-10 08:05 UTC, FirstBroRussia commented on js/photo-filtering.js
> +  let setTimeOutOperation;
это и есть функция setTimeout

2021-11-10 08:05 UTC, FirstBroRussia commented on js/photo-filtering.js
> +      }, 500);
+

2021-11-10 08:08 UTC, FirstBroRussia commented on js/render-full-picture.js
> +  if (currentPhoto) {
+++

2021-11-10 08:24 UTC, FirstBroRussia commented on js/render-full-picture.js
> +  if (currentPhoto) {
Вот здесь есть обработчик на весь родитель, где лежит `evt.target.closest('a[class="picture"]')`, тогда если эту проверку убрать, то появляется ошибка в консоли, так как клики по другой области ее не удовлетворяют

2021-11-10 10:15 UTC, merged